### ISSUE TITLE
Jest Unit Tests Failing Due to 'export' Symbol.

### ISSUE THREAD

**Issue by mcampbellxperi** [microsoft/react-native-xaml#188]
### Problem Description

When running my jest unit tests, any component that includes a react-native-xaml component will cause the unit test case to fail with the following error:
```
C:\Users\PathToMyProject\node_modules\react-native-xaml\lib\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './NativeXamlControl';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token 'export'

    > 50 | import {Path} from 'react-native-xaml';
         | ^
      51 |

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (component.tsx:50:1)
```
After reading online I found this documentation from jest RE external dependencies https://jestjs.io/docs/tutorial-react-native#transformignorepatterns-customization

I updated my package.json with the following:
```
 "jest": {
    "preset": "react-native",
    "moduleFileExtensions": ["ts", "tsx", "js", "jsx", "json", "node"],
    "setupFilesAfterEnv": ["@testing-library/jest-native/extend-expect"],
    "transformIgnorePatterns": [
      "node_modules/(?!(@react-native|react-native|my-project|react-native-xaml)/)"
    ],
    "transform": { "^.+\\.(js|jsx)$": "babel-jest"}
  }
```

This results in the following error:
```
 ● Test suite failed to run

    TypeError: Cannot read property 'Commands' of undefined

      at Object.<anonymous> (node_modules/react-native-xaml/src/Types.tsx:187:22)
      at Object.<anonymous> (node_modules/react-native-xaml/src/index.ts:2:1)
```

Is there any advice on how to fix these issues or a way to have react-native-xaml work with jest out of the box?

### Steps To Reproduce

1. Create a react component containing a react-native-xaml component. We have used `<Path>` in our project.
2. Create a jest unit test to test the new component.
3. Run `jest test`
4. The unit test will fail with the error described in Problem Description.

### Expected Results

I expect that my unit tests will pass/fail based on my own code. Not fail due to an import error.

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 19.06 GB / 31.78 GB
  Binaries:
    Node: 14.17.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.31605.320 (Visual Studio Professional 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.66.3 => 0.66.3
    react-native-windows: 0.66.5 => 0.66.5
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by chrisglein** [comment]
This looks like a mix of ES6 and CommonJS modules. This might be addressable with your babel config. What are your full set of dependencies and version of jest? Can you break out a standalone sample project that we can look at?
